# Generated by Django 3.2.9 on 2022-02-06 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='filedellist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('filedir', models.TextField(blank=True, max_length=4096, null=True, verbose_name='路径')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '已删除文件',
                'verbose_name_plural': '已删除文件',
            },
        ),
        migrations.CreateModel(
            name='messgaelist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('code', models.CharField(max_length=5, unique=True, verbose_name='代码')),
                ('typetf', models.CharField(choices=[('t', 'text'), ('f', 'file')], max_length=1, verbose_name='类型')),
                ('file', models.FileField(blank=True, null=True, upload_to='file/89b1dc16-8ffd-4b97-8cda-825de69463aa/', verbose_name='文件')),
                ('text', models.TextField(blank=True, max_length=4096, null=True, verbose_name='文本')),
                ('time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '消息列表',
                'verbose_name_plural': '消息列表',
            },
        ),
        migrations.CreateModel(
            name='settingslist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='id')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='键')),
                ('val', models.CharField(max_length=100, verbose_name='值')),
                ('oth', models.CharField(blank=True, max_length=200, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '设置参数',
                'verbose_name_plural': '设置参数',
            },
        ),
    ]
