# Generated by Django 3.2.9 on 2022-03-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messgaelist',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='file/773bee95-52d6-40df-9bf9-33dbfa46697a/', verbose_name='文件'),
        ),
    ]
